default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  username: postgres
  password:

development:
  <<: *default
  database: memorizationalize_dev

test:
  <<: *default
  database: memorizationalize_test

production:
  <<: *default
  database: memorizationalize_prod
