# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16376d636740f7811e23699b4c6e074f798756c8e29c4feb13ee5e1ca4bc6d5a715976c474cec05be9293b507d076b16f2cf2c1d6ebe0724023cdbd365d1bbf5

test:
  secret_key_base: 44198a78f1aa6f300770766c1d2d943b711da4af1d4ff269dd8bc3a8387c6587cfe06d67c2e3eef61809bcb48bcfe890a0055fa68d903078ac15470fb5524642

staging:
  secret_key_base: 0;~-qW[K<6wrURR&z\-LTpA=[#N..z:9/I<UqkM(18NV.TpSd#Gks|(P<hMl2$V!Fc+=EkWnOe|zR+QPBhoejsei^0_}dw4I/e?G62@8.QHa:QSJ\_-r%dyUbh6T(EVK

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
